/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    categories: Category;
    products: Product;
    'product-variants': ProductVariant;
    orders: Order;
    'gift-cards': GiftCard;
    'gift-card-redemptions': GiftCardRedemption;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'gift-cards': GiftCardsSelect<false> | GiftCardsSelect<true>;
    'gift-card-redemptions': GiftCardRedemptionsSelect<false> | GiftCardRedemptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'admin' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  /**
   * Set automatically when the customer first checks out. Don't edit.
   */
  stripeCustomerId?: string | null;
  newsletterOptIn?: boolean | null;
  addresses?:
    | {
        /**
         * e.g. Home, Office
         */
        label?: string | null;
        recipientName: string;
        line1: string;
        line2?: string | null;
        city: string;
        region: string;
        postalCode: string;
        country: string;
        phone?: string | null;
        isDefault?: boolean | null;
        type?: ('shipping' | 'billing' | 'both') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-fills from the name. Only edit if you know what you're doing.
   */
  slug: string;
  /**
   * Short blurb shown on the category page.
   */
  description?: string | null;
  /**
   * Shown at the top of the category page.
   */
  image?: (number | null) | Media;
  /**
   * Leave blank for top-level categories. Pick a parent to nest this one under it.
   */
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Auto-fills from the name. Only edit if you know what you're doing.
   */
  slug: string;
  /**
   * The main copy on the product page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: number | Category;
  /**
   * Stored as integer cents.
   */
  basePrice: number;
  /**
   * Drag to reorder. First photo is the main image. Optional — you can save a draft and add photos later.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Drafts and archived products aren't visible on the storefront.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Shown as the browser tab title and the Google result heading.
   */
  seoTitle?: string | null;
  /**
   * The blurb under the title in search results.
   */
  seoDescription?: string | null;
  /**
   * Used when this page is shared on social media. Square or landscape works best.
   */
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  product: number | Product;
  /**
   * Inventory code for this specific variant.
   */
  sku: string;
  /**
   * e.g. S, M, L, XL — leave blank if this variant isn't size-specific.
   */
  size?: string | null;
  color?: string | null;
  /**
   * Optional. If set, this overrides the product's base price for this variant. Stored as integer cents.
   */
  price?: number | null;
  /**
   * How many of this variant we have on hand.
   */
  inventoryCount: number;
  /**
   * Optional. Falls back to the product's main photos if blank.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All purchases. Created automatically by the Stripe webhook — don't add orders by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Payment status. Set by the Stripe webhook.
   */
  status: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * Where the package is. Update this as you ship.
   */
  fulfillmentStatus: 'unfulfilled' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * Blank for guest checkouts.
   */
  customer?: (number | null) | Customer;
  /**
   * Email used at checkout when there was no customer account.
   */
  guestEmail?: string | null;
  lineItems?:
    | {
        product: number | Product;
        variant?: (number | null) | ProductVariant;
        nameSnapshot: string;
        skuSnapshot?: string | null;
        quantity: number;
        /**
         * What the customer paid per unit. Stored as integer cents.
         */
        priceAtPurchase: number;
        id?: string | null;
      }[]
    | null;
  subtotal: number;
  tax: number;
  shipping: number;
  giftCardDiscount: number;
  total: number;
  shippingAddress: {
    recipientName: string;
    line1: string;
    line2?: string | null;
    city: string;
    region: string;
    postalCode: string;
    country: string;
    phone?: string | null;
  };
  billingAddress: {
    recipientName: string;
    line1: string;
    line2?: string | null;
    city: string;
    region: string;
    postalCode: string;
    country: string;
    phone?: string | null;
  };
  trackingNumber?: string | null;
  /**
   * e.g. USPS, UPS, FedEx
   */
  carrier?: string | null;
  stripePaymentIntentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gift cards sold or manually issued. Codes auto-generate on create.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards".
 */
export interface GiftCard {
  id: number;
  /**
   * Unique 16-character code. Auto-generated on create — don't edit.
   */
  code: string;
  /**
   * The amount the gift card was purchased for. Stored as integer cents.
   */
  initialValue: number;
  /**
   * Remaining balance. Decremented by the redemption system — don't edit by hand.
   */
  currentBalance: number;
  status: 'active' | 'redeemed' | 'expired';
  recipientName: string;
  recipientEmail: string;
  /**
   * Personal note included with the gift card email.
   */
  message?: string | null;
  /**
   * When the recipient gets the email. Defaults to immediate if blank.
   */
  deliveryDate?: string | null;
  /**
   * Blank if a non-account guest bought the gift card.
   */
  purchaser?: (number | null) | Customer;
  /**
   * Defaults to one year after purchase.
   */
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only audit log of every gift card application.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-card-redemptions".
 */
export interface GiftCardRedemption {
  id: number;
  giftCard: number | GiftCard;
  order: number | Order;
  /**
   * Stored as integer cents.
   */
  amountUsed: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'gift-cards';
        value: number | GiftCard;
      } | null)
    | ({
        relationTo: 'gift-card-redemptions';
        value: number | GiftCardRedemption;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  stripeCustomerId?: T;
  newsletterOptIn?: T;
  addresses?:
    | T
    | {
        label?: T;
        recipientName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
        isDefault?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  basePrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  size?: T;
  color?: T;
  price?: T;
  inventoryCount?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  fulfillmentStatus?: T;
  customer?: T;
  guestEmail?: T;
  lineItems?:
    | T
    | {
        product?: T;
        variant?: T;
        nameSnapshot?: T;
        skuSnapshot?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  shipping?: T;
  giftCardDiscount?: T;
  total?: T;
  shippingAddress?:
    | T
    | {
        recipientName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        recipientName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  trackingNumber?: T;
  carrier?: T;
  stripePaymentIntentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards_select".
 */
export interface GiftCardsSelect<T extends boolean = true> {
  code?: T;
  initialValue?: T;
  currentBalance?: T;
  status?: T;
  recipientName?: T;
  recipientEmail?: T;
  message?: T;
  deliveryDate?: T;
  purchaser?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-card-redemptions_select".
 */
export interface GiftCardRedemptionsSelect<T extends boolean = true> {
  giftCard?: T;
  order?: T;
  amountUsed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}